services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    image: leoalmeida/frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express

networks:
  react-express: