name: Docker Hub Image

on:
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.10.0
    - name: Docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWD }}
    - name: Docker push frontend
      uses: docker/build-push-action@v6.15.0
      with:
        file: ./Dockerfile
        context: frontend
        push: true
        tags: leoalmeida/frontend:${{github.run_number}}
