# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Portal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm ci

    - name: Verificando código (lint)
      run: npm run lint

    - name: Test
      run: npm test
  
  zap-scan:
    needs: test-frontend
    uses: ./.github/workflows/zap_scan.yml
    secrets: inherit

  docker:
    needs: test-frontend
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
  
 # deploy_ecs:
 #   needs: docker
 #   uses: ./.github/workflows/ECS.yml
 #   secrets: inherit
