name: OWASP zap_scan

on:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan Baseline
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fazer Build da aplicação de teste
      run: docker compose build
    - name: Subir a aplicação de teste local
      run: docker compose up -d
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.12.0
      env: 
          INSTANCE_IP: localhost
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "http://${{ env.INSTANCE_IP }}:3000"
          cmd_options: |
            chmod a+rwx '/zap/wrk/zap.yaml'
          allow_issue_writing: false 
    # Docs: https://github.com/actions/upload-artifact
    - name: Upload Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: zap_report.html
        path: .
        retention-days: 5
